/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/cloud/model.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Cloud({ opacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/cloud/model.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mball001.geometry}>
        <meshStandardMaterial
          {...materials["lambert2SG.001"]}
          envMapIntensity={2}
          transparent
          opacity={opacity}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/cloud/model.gltf");
