import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Experience from "@/components/Experience";
import { Canvas } from "@react-three/fiber";
import styled from "styled-components";
import { ScrollControls } from "@react-three/drei";

const Container = styled.main`
  width: 100vw;
  height: 100vh;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Flying with me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Canvas>
          <color attach={"background"} args={["#ececec"]} />
          <ScrollControls pages={20} damping={0.5}>
            <Experience />
          </ScrollControls>
        </Canvas>
      </Container>
    </>
  );
}
