import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Experience from "@/components/Experience";
import { Canvas } from "@react-three/fiber";
import styled from "styled-components";
import { ScrollControls } from "@react-three/drei";
import Overlay from "@/components/Overlay";

const Container = styled.main`
  width: 100vw;
  height: 100vh;
`;

const NoiseOverlay = styled.div`
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  background: url(./images/Noise.png);
  opacity: 0.1;
  z-index: 1;
  pointer-events: none;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Flying with Displore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./images/Displore-logo.png" />
      </Head>
      <Container>
        <NoiseOverlay />
        <Canvas>
          <color attach={"background"} args={["#ececec"]} />
          <ScrollControls pages={20} damping={0.5}>
            <Experience />
          </ScrollControls>
        </Canvas>
        <Overlay />
      </Container>
    </>
  );
}
